"""
Generate the PWA icons.

Android will not offer "Add to Home screen" without a >=192px icon, and without that there is
no share target — so these are load-bearing, not decoration.

Written by hand with zlib rather than pulling in an image library: two flat PNGs do not justify
a dependency, and this way the icons are reproducible from source.

Run: python3 scripts/generate-icons.py
"""
import base64
import io
import struct
import zlib

ACCENT = (0x1F, 0x5F, 0xBF)
WHITE = (0xFF, 0xFF, 0xFF)


def make_inside(size, radius):
    """
    True inside a rounded square.

    Clamps the point to the inner rectangle and measures the distance to that clamped point —
    which is zero along the straight edges and a true radial distance in the corners. Simpler
    and symmetric, unlike per-corner special casing.
    """
    lo, hi = radius, size - 1 - radius

    def inside(x, y):
        cx = lo if x < lo else (hi if x > hi else x)
        cy = lo if y < lo else (hi if y > hi else y)
        dx, dy = x - cx, y - cy
        return dx * dx + dy * dy <= radius * radius

    return inside


def draw(size):
    """An 'L' mark on a rounded accent square. Deliberately plain: it must read at 48px."""
    radius = int(size * 0.22)
    inside = make_inside(size, radius)

    stroke = max(3, round(size * 0.13))
    left = round(size * 0.31)
    top = round(size * 0.23)
    bottom = round(size * 0.77)
    right = round(size * 0.70)

    rows = []
    for y in range(size):
        row = bytearray()
        for x in range(size):
            if not inside(x, y):
                row += b'\x00\x00\x00\x00'  # transparent outside the rounded square
                continue
            on_stem = left <= x < left + stroke and top <= y <= bottom
            on_foot = bottom - stroke < y <= bottom and left <= x <= right
            row += bytes(WHITE + (255,)) if (on_stem or on_foot) else bytes(ACCENT + (255,))
        rows.append(bytes(row))

    raw = b''.join(b'\x00' + r for r in rows)  # filter byte 0 per scanline

    def chunk(tag, data):
        return (
            struct.pack('>I', len(data))
            + tag
            + data
            + struct.pack('>I', zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    png = b'\x89PNG\r\n\x1a\n'
    png += chunk(b'IHDR', struct.pack('>IIBBBBB', size, size, 8, 6, 0, 0, 0))  # 8-bit RGBA
    png += chunk(b'IDAT', zlib.compress(raw, 9))
    png += chunk(b'IEND', b'')
    return png


out = io.StringIO()
out.write('''/**
 * PWA icons, embedded as base64.
 *
 * Embedded rather than served as static files because the two deploy targets handle static
 * assets differently, and two small PNGs in the bundle keeps one code path for both.
 *
 * Generated by scripts/generate-icons.py — edit that, not this.
 */

''')
for size in (192, 512):
    data = draw(size)
    b64 = base64.b64encode(data).decode()
    out.write(f'export const ICON_{size}_PNG_BASE64 =\n')
    for i in range(0, len(b64), 96):
        suffix = "' +" if i + 96 < len(b64) else "';"
        out.write(f"  '{b64[i:i+96]}{suffix}\n")
    out.write('\n')
    print(f'  {size}x{size}: {len(data)} bytes')

open('src/http/icons.ts', 'w').write(out.getvalue())
print('wrote src/http/icons.ts')
