#!/usr/bin/env node
/**
 * `pnpm setup` — write a .env with the three generated secrets already filled in.
 *
 * These three are pure entropy: there is nothing to decide, nothing to look up, and no reason a
 * human should be running `openssl` three times and pasting the results into the right lines.
 * The two that *are* decisions — the Google client ID and secret — cannot be generated by
 * anybody but you, so this script names them and stops.
 *
 * Safe to run repeatedly. It never overwrites a value that is already set, because
 * TOKEN_ENCRYPTION_KEY in particular is the difference between "your stored Google token still
 * decrypts" and "everyone re-authorises".
 */

import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = join(root, '.env');
const examplePath = join(root, '.env.example');

/** URL-safe, no padding — it travels in an Authorization header and in Shortcut config. */
const base64url = (bytes) => randomBytes(bytes).toString('base64url');
/** Standard base64: the vault decodes exactly 32 bytes from this. */
const base64 = (bytes) => randomBytes(bytes).toString('base64');

const GENERATED = {
  INGEST_TOKEN: () => base64url(32),
  TOKEN_ENCRYPTION_KEY: () => base64(32),
  SESSION_SECRET: () => base64(32),
};

const MANUAL = {
  GOOGLE_CLIENT_ID: 'ends in .apps.googleusercontent.com',
  GOOGLE_CLIENT_SECRET: 'starts with GOCSPX-',
};

const bold = (s) => `\u001b[1m${s}\u001b[0m`;
const dim = (s) => `\u001b[2m${s}\u001b[0m`;
const green = (s) => `\u001b[32m${s}\u001b[0m`;
const yellow = (s) => `\u001b[33m${s}\u001b[0m`;

function valueOf(contents, key) {
  // Last assignment wins, matching how dotenv loaders behave.
  const matches = [...contents.matchAll(new RegExp(`^${key}=(.*)$`, 'gm'))];
  return matches.at(-1)?.[1]?.trim() ?? undefined;
}

function setValue(contents, key, value) {
  const line = `${key}=${value}`;
  return new RegExp(`^${key}=.*$`, 'm').test(contents)
    ? contents.replace(new RegExp(`^${key}=.*$`, 'm'), line)
    : `${contents.trimEnd()}\n${line}\n`;
}

function main() {
  if (!existsSync(examplePath)) {
    console.error('.env.example is missing — are you in the repository root?');
    process.exit(1);
  }

  const created = !existsSync(envPath);
  let contents = created ? readFileSync(examplePath, 'utf8') : readFileSync(envPath, 'utf8');

  console.log(`\n  ${bold('Later — setup')}\n`);
  if (created) console.log(`  Created ${bold('.env')} from .env.example\n`);
  else console.log(`  Found an existing ${bold('.env')}. Nothing already set will be changed.\n`);

  const generated = [];
  for (const [key, make] of Object.entries(GENERATED)) {
    if (valueOf(contents, key)) {
      console.log(`  ${dim('·')} ${key.padEnd(22)} ${dim('already set, left alone')}`);
      continue;
    }
    contents = setValue(contents, key, make());
    generated.push(key);
    console.log(`  ${green('✓')} ${key.padEnd(22)} ${green('generated')}`);
  }

  writeFileSync(envPath, contents, { mode: 0o600 });

  const missing = Object.keys(MANUAL).filter((key) => !valueOf(contents, key));

  if (missing.length === 0) {
    console.log(`\n  ${green('Everything required is set.')} Start it with:\n`);
    console.log(`      ${bold('pnpm dev')}\n`);
    console.log(`  Then open http://localhost:8787 and click "Connect Google".\n`);
    return;
  }

  console.log(`\n  ${yellow('Two values I cannot generate for you:')}\n`);
  for (const key of missing) console.log(`      ${bold(key.padEnd(22))} ${dim(MANUAL[key])}`);
  console.log(`
  They come from a Google Cloud OAuth client, which only exists inside your own
  Google account. Creating one is free, takes about 15 minutes, needs no card,
  and the exact click path is in:

      ${bold('docs/ACTION-REQUIRED.md')}  ${dim('— Batch 1')}

  ${bold('Want to see Later work before doing any of that?')} You do not need them:

      ${bold('USE_FIXTURES=true pnpm dev')}

  That runs the whole pipeline against recorded responses. Nothing reaches
  Google, no credentials exist, and no real playlist is touched.
`);
}

main();
